version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./nginx-ws/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - websocket

  go_ws_server1:
    build:
      context: ./go-ws-server
      dockerfile: Dockerfile
    container_name: go_ws_server1
    restart: unless-stopped
    ports:
      - 8010:8010
    networks:
      - websocket

  go_ws_server2:
    build:
      context: ./go-ws-server
      dockerfile: Dockerfile
    container_name: go_ws_server2
    restart: unless-stopped
    ports:
      - 8020:8010
    networks:
      - websocket

  wscat1:
    build:
      context: ./wscat-ws
      dockerfile: Dockerfile
    container_name: wscat1
    networks:
      - websocket
  wscat2:
    build:
      context: ./wscat-ws
      dockerfile: Dockerfile
    container_name: wscat2
    networks:
      - websocket

networks:
  websocket: